# Generated by Django 5.1 on 2024-08-08 10:28

import Banking_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('account_no', models.CharField(default=Banking_app.models.gen_ac_no, editable=False, max_length=100)),
                ('ac_balance', models.FloatField(default=1000)),
                ('ph_number', models.IntegerField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
