# Generated by Django 5.1 on 2024-08-08 11:10

import Banking_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_no',
            field=models.CharField(default=Banking_app.models.gen_ac_no, editable=False, max_length=100, unique=True),
        ),
    ]
