# Generated by Django 5.1 on 2024-08-09 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_app', '0004_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date-Of-Birth(YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='ph_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be 10 digits.')]),
        ),
    ]
